### ISSUE TITLE
Bosca Ceoil online not working on a Chromebook

### ISSUE THREAD

**Issue by spxtator** [dy-dx/boscaceoil-online#5]
Bosca ceoil does not work on Chromebooks. They do have flash. I have to whitelist the URL for it to work on my at home computer. I have done that here and it still doesn't work after refreshing and restarting (chrome its self, and the computer). Does it run on air? Java???

**Comment by pineapplebox** [comment]
I am guessing that there is no way to enable flash, as this is what happened to me. for this reason I have created a bookmarklet as a solution, however, I am hoping this will be temporary and the developers can fix this soon. Heres the bookmarklet code, just use it whenever you go onto the website:
`javascript:document.write("<br><br><br><br><br><center><a href='http://get.adobe.com/flashplayer/'>Enable Flash Player</a></center>");`

**Comment by spxtator** [comment]
Hi, 

This issue is no irreverent and out of date. 

I will be closing this now.
